### ISSUE TITLE
iPad issue: Help layer shows wrong help-texts. 

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#244] opened 2015-07-24 09:23 UTC
Help layers help-texts show "edit board"-texts even when I have no edit board-button (i'm a guest). 

////////CONTRIBOARD TESTING, 24.7.2015////////

Contriboard (SUT) versions:
Client version v1.2.100
API version v0.4.38
IMG version v0.1.10

Testing environment:
Heli (1 kpl iPad iOS 8.3 (12F69) Flowdock -> Apple web-view)

////////CONTRIBOARD TESTING, 24.7.2015////////

**Comment by tanelih** [comment] 2015-07-24 09:42
Duplicate of #246

**Comment by narsuman** [comment] 2015-07-29 05:40
Duplicate #246 Closed now

Client versio   v1.2.118
API versio  v0.4.42
IMG versio  v0.1.10

**Closed as completed by narsuman** 2015-07-29 05:40 UTC
Labels: bug, duplicate
